name: Build web page
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate html pages
        run: python3 mkindex.py
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: 'ssh.strato.de'
          port: 22
          username: ${{ secrets.SFTP_UPLOAD_USER }}
          password: ${{ secrets.SFTP_UPLOAD_PASSWORD }}
          localPath: './src'
          remotePath: './rezepte'
